import Footer from "@/components/footer/footer";
import Header from "@/components/header/header";
import HambMenuProvider from "@/context/hamburgerContext";
import "animate.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { TanstackProvider } from "@/components/providers/tanstack-provider";
import FilterSortProvider from "@/context/filterSortContext";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-gray-300`}>
        <TanstackProvider>
          <FilterSortProvider>
            <HambMenuProvider>
              <Header />
              {children}
              <Footer />
            </HambMenuProvider>
          </FilterSortProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
