export const categories = [
  {
    id: 1,
    name: "Computers",
    image: "/category/computers.webp",
    alt: "Laptop computer with colorful display",
    text: "Computers",
    href: "/categories/computers",
  },
  {
    id: 2,
    name: "Mobile",
    image: "/category/mobiles.webp",
    alt: "Modern smartphone with gradient display",
    text: "Mobile",
    href: "/categories/mobile",
  },
  {
    id: 3,
    name: "Drones & Cameras",
    image: "/category/drones.webp",
    alt: "Quadcopter drone with camera",
    text: "Drones & Cameras",
    href: "/categories/drones-cameras",
  },
  {
    id: 4,
    name: "Tablets",
    image: "/category/tablets.webp",
    alt: "Tablet device with colorful display",
    text: "Tablets",
    href: "/categories/tablets",
  },
  {
    id: 5,
    name: "TV & Home Cinema",
    image: "/category/tvs.webp",
    alt: "Modern flatscreen TV with colorful display",
    text: "T.V & Home Cinema",
    href: "/categories/tv-home-cinema",
  },
  {
    id: 6,
    name: "Wearable Tech",
    image: "/category/wearable.webp",
    alt: "Smart watch with digital display",
    text: "Wearable Tech",
    href: "/categories/wearable-tech",
  },
  {
    id: 7,
    name: "Speakers",
    image: "/category/speakers.webp",
    alt: "Black cylindrical wireless speaker",
    text: "Speakers",
    href: "/categories/speakers",
  },
  {
    id: 8,
    name: "Headphones",
    image: "/category/headphones.webp",
    alt: "Black wireless earbuds",
    text: "Headphones",
    href: "/categories/headphones",
  },
];
